In [1]:
import jax
import jax.numpy as jnp

In [14]:
def _interpolate(idxs, values):
    """
    Interpolate values at given indices.

    Args:
        idxs: should be fractional, between 0 and 1
        values: values to interpolate, assumed to be evenly spaced between 0 and 1
    """
    idxs = idxs * (values.shape[0] - 1)
    idxs_floor = jnp.floor(idxs)
    idxs_ceil = jnp.ceil(idxs)
    idxs_frac = idxs - idxs_floor.astype(jnp.float32)
    idxs_floor = idxs_floor.astype(jnp.int32)
    idxs_ceil = idxs_ceil.astype(jnp.int32)
    values_floor = jnp.take(values, idxs_floor, axis=0)
    values_ceil = jnp.take(values, idxs_ceil, axis=0)
    idxs_frac = idxs_frac[..., None]
    return (1 - idxs_frac) * values_floor + idxs_frac * values_ceil

In [39]:
idxs = jnp.array([0.5, 0., 0.99])
values = jnp.arange(50).reshape(5,10).astype(jnp.float32)
idxs, values

(Array([0.5 , 0.  , 0.99], dtype=float32),
 Array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]], dtype=float32))

In [38]:
%%time
_interpolate(idxs, values)

(2, 3, 1) (2, 3, 10) (2, 3, 10)
CPU times: user 3.82 ms, sys: 3.93 ms, total: 7.75 ms
Wall time: 3.54 ms


Array([[[20.      , 21.      , 22.      , 23.      , 24.      ,
         25.      , 26.      , 27.      , 28.      , 29.      ],
        [ 0.      ,  1.      ,  2.      ,  3.      ,  4.      ,
          5.      ,  6.      ,  7.      ,  8.      ,  9.      ],
        [39.6     , 40.6     , 41.6     , 42.600002, 43.6     ,
         44.6     , 45.600002, 46.600002, 47.6     , 48.6     ]],

       [[20.      , 21.      , 22.      , 23.      , 24.      ,
         25.      , 26.      , 27.      , 28.      , 29.      ],
        [ 0.      ,  1.      ,  2.      ,  3.      ,  4.      ,
          5.      ,  6.      ,  7.      ,  8.      ,  9.      ],
        [39.6     , 40.6     , 41.6     , 42.600002, 43.6     ,
         44.6     , 45.600002, 46.600002, 47.6     , 48.6     ]]],      dtype=float32)

In [40]:
jit_f = jax.jit(_interpolate)

In [43]:
%%time
jit_f(idxs, values)

CPU times: user 187 µs, sys: 1.13 ms, total: 1.31 ms
Wall time: 650 µs


Array([[20.      , 21.      , 22.      , 23.      , 24.      , 25.      ,
        26.      , 27.      , 28.      , 29.      ],
       [ 0.      ,  1.      ,  2.      ,  3.      ,  4.      ,  5.      ,
         6.      ,  7.      ,  8.      ,  9.      ],
       [39.6     , 40.6     , 41.6     , 42.600002, 43.6     , 44.6     ,
        45.600002, 46.600002, 47.6     , 48.6     ]], dtype=float32)

In [44]:
idxs = jnp.array([[0.5, 0., 0.99],[0.5, 0., 0.99]])
values = jnp.arange(50).reshape(5,10).astype(jnp.float32)
idxs, values

(Array([[0.5 , 0.  , 0.99],
        [0.5 , 0.  , 0.99]], dtype=float32),
 Array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]], dtype=float32))

In [46]:
_interpolate(idxs, values)

(2, 3, 1) (2, 3, 10) (2, 3, 10)


Array([[[20.      , 21.      , 22.      , 23.      , 24.      ,
         25.      , 26.      , 27.      , 28.      , 29.      ],
        [ 0.      ,  1.      ,  2.      ,  3.      ,  4.      ,
          5.      ,  6.      ,  7.      ,  8.      ,  9.      ],
        [39.6     , 40.6     , 41.6     , 42.600002, 43.6     ,
         44.6     , 45.600002, 46.600002, 47.6     , 48.6     ]],

       [[20.      , 21.      , 22.      , 23.      , 24.      ,
         25.      , 26.      , 27.      , 28.      , 29.      ],
        [ 0.      ,  1.      ,  2.      ,  3.      ,  4.      ,
          5.      ,  6.      ,  7.      ,  8.      ,  9.      ],
        [39.6     , 40.6     , 41.6     , 42.600002, 43.6     ,
         44.6     , 45.600002, 46.600002, 47.6     , 48.6     ]]],      dtype=float32)